## ALARM CONTROL PANEL
- platform: manual
  name: Alarm
  delay_time: 120
  arming_time: 15
  trigger_time: 1200
  code_arm_required: false
  arming_states: 
    - armed_away
    - armed_home
# - platform: manual
#   name: Fridge
#   delay_time: 60
#   trigger_time: 1200
#   code_arm_required: false
  