# - platform: miflora
#   mac: 'C4:7C:8D:63:4B:41'
#   name: Flower
#   force_update: false
# #  median: 5
#   monitored_conditions:
#     - moisture
#     - light
#     - temperature
#     - conductivity
#     - battery
